# -*- coding: utf-8 -*-
D = dict(
    title="Maya Logistics Inc | Locuri de muncă CDL-A | Angajăm șoferi — 48 de state",
    desc="Maya Logistics Inc angajează șoferi CDL clasa A și owner-operatori. Plată 70–72¢ pe milă sau 30–32% din brut, camioane noi 2026, dry van și power only, toate cele 48 de state, dispecerat în cinci limbi.",
    og_title="Maya Logistics Inc — angajăm șoferi CDL clasa A",
    og_desc="70–72¢ pe milă sau 30–32% din brut. Camioane noi 2026, dry van și power only, 48 de state, dispecerat în cinci limbi.",

    nav_menu="Meniu",
    nav_positions="Posturi",
    nav_pay="Plată",
    nav_req="Cerințe",
    nav_platform="Platformă",
    nav_company="Compania",
    lang_label="Limba",

    cta_apply="Vreau să conduc",
    cta_freight="Am marfă de transportat",
    cta_write="Scrieți-ne",

    hero_eyebrow="Maya Logistics Inc — transportator american",
    hero_h1="Angajăm <em>șoferi CDL-A</em> și owner-operatori.",
    hero_lead="Dry van și power only în toate cele 48 de state, sub autoritatea noastră din 2007. Două variante de plată la alegere, camioane noi din 2026 și un dispecer care chiar vorbește limba ta — non-stop.",
    chip_cpm="Până la <b>70–72¢</b> pe milă",
    chip_pct="sau <b>30–32%</b> din brut",
    chip_trucks="Camioane noi <b>2026</b>",
    chip_states="<b>48</b> de state",

    pos_eyebrow="Posturi de șofer",
    pos_h2="Alege felul în care vrei să rulezi.",
    pos_lead="Aceeași marfă, același dispecerat, aceleași 48 de state — diferă doar felul în care conduci și felul în care ești plătit.",
    pos_solo="Tu și camionul, de la un ocean la altul. Mile constante pe dry van de 53 de picioare și power only, plătite pe milă sau procentual.",
    pos_team="Lucrați în echipaj de doi și camionul aproape nu stă. Curse mai lungi, mai multe mile pe săptămână, împărțite cum vă înțelegeți.",
    pos_oo="Vino cu propriul camion sub autoritatea noastră sau trage remorcile noastre în power only. Plată procentuală, fără dispecerat forțat.",
    pos_solo_alt="Cap tractor cu remorcă dry van pe autostradă, seara",
    pos_team_alt="Cap tractor cu remorcă la apus",
    pos_oo_alt="Cap tractor pe o autostradă din deșert și drapelul american",

    pay_eyebrow="Plată și echipament",
    pay_h2="Ce primești <em>conducând la Maya</em>.",
    pay_lead="Fără scris mărunt: alegi varianta de plată înainte de a porni și nu se schimbă pentru că a ieșit o săptămână slabă.",
    pay_cpm_t="Pe milă",
    pay_cpm_d="Plata maximă pe milă pentru șoferii companiei, pe marfă dry van și power only.",
    pay_pct_t="Din brut",
    pay_pct_d="Preferi procentul? Iei o parte din cât plătește cu adevărat cursa.",
    pay_new_t="Camioane noi",
    pay_new_d="Capete tractor noi care intră în flotă anul acesta, cu remorci dry van de 53 de picioare.",
    pay_lang_t="Limbi la dispecerat",
    pay_lang_d="Engleză, spaniolă, ucraineană, rusă și română — vorbește așa cum gândești.",
    pay_disp_t="Dispecerul tău",
    pay_disp_d="Un om care te cunoaște pe tine și camionul tău, nu o coadă și un număr de tichet. Non-stop pentru marfa aflată în cursă.",
    pay_eld_t="ELD, fără foi de parcurs pe hârtie",
    pay_eld_d="Fiecare unitate are ELD. Orele și poziția vin de la camion, așa că nimeni nu se ceartă pe ceas.",
    pay_eq_t="Dry van și power only",
    pay_eq_d="Remorci de 53 de picioare și curse power only. Marfă generală, fără mărfuri periculoase — nu trebuie alergat după endorsement-uri.",
    pay_48_t="Toate cele 48 de state",
    pay_48_d="Mile reale de la un ocean la altul. Spune-ne în ce zonă vrei să rulezi și planificăm în jurul ei.",

    req_eyebrow="Cerințe",
    req_h2="De ce ai nevoie ca să începi.",
    req_lead="Lista e scurtă și o parcurgem împreună chiar la primul telefon.",
    req_1_t="CDL clasa A", req_1_d="Valabil, emis în orice stat.",
    req_2_t="Fișă medicală DOT", req_2_d="Valabilă în ziua în care începi.",
    req_3_t="Drept de muncă în S.U.A.", req_3_d="Documentele pregătite pentru dosar.",
    req_4_t="Istoric de condus acceptabil", req_4_d="MVR și dosarul DOT, pe care le verificăm înainte de plecare.",
    req_5_t="Disponibil pentru OTR", req_5_d="Te simți bine rulând prin cele 48 de state și stând pe drum.",
    req_alt="Cap tractor pe o autostradă printre stânci roșii",

    apply_eyebrow="Formular de angajare",
    apply_h2="Spune-ne despre tine.",
    apply_lead="Completează și îți răspundem în aceeași zi lucrătoare. Pe site nu se salvează nimic: formularul doar scrie scrisoarea în locul tău, gata de trimis din Gmail sau din programul tău de e-mail.",
    apply_direct="Preferi să scrii direct?",
    apply_subject="Formular de angajare — Maya Logistics",
    apply_ready="Formularul este gata",
    f_name="Nume și prenume", f_phone="Telefon", f_email="E-mail", f_pos="Postul",
    f_cdl="Statul CDL", f_exp="Experiență OTR", f_exp_ph="de exemplu, 3 ani",
    f_msg="Ce ar mai trebui să știm", f_send="Trimite formularul",
    f_privacy="Folosim datele trimise doar ca să te contactăm în legătură cu munca la Maya Logistics.",

    comp_eyebrow="Despre Maya",
    comp_h2="Transportator, nu intermediar.",
    comp_p1="Maya Logistics Inc este un transportator american cu flotă proprie, cu baza în Cleveland, Tennessee. Avem autoritate interstatală proprie din 2007 și rulăm cu camioanele noastre și cu șoferii noștri — nu revindem marfa nimănui.",
    comp_p2="Dispeceratul este al nostru și lucrează non-stop, așa că răspunsul primit de șofer și cel primit de client sunt unul și același.",
    comp_since="Pe drum din", comp_states="State", comp_desk="Dispecerat",
    comp_alt="Capete tractor aliniate în curtea terminalului",

    ship_eyebrow="Expeditori și brokeri",
    ship_h2="Aveți nevoie de un camion?",
    ship_lead="Trimiteți ruta, tipul mărfii, greutatea și fereastra de încărcare — primiți tarif și camion în aceeași zi lucrătoare, de la un transportator care își deține echipamentul.",
    ship_t1="Dry van de 53'", ship_t2="Power only", ship_t3="Camion complet",
    ship_t4="48 de state", ship_t5="Urmărire ELD pe fiecare unitate",
    ship_btn="Cereți un tarif pe e-mail",
    ship_packet="Ne înregistrați ca transportator? Cereți și pachetul complet ajunge direct la departamentul dumneavoastră de conformitate, cu firma dumneavoastră trecută ca deținător al certificatului.",

    plat_eyebrow="Tehnologia noastră",
    plat_h2="Dispeceratul care ține Maya în mișcare, <em>scris de noi</em>.",
    plat_p1="Majoritatea transportatorilor de mărimea noastră lucrează cu tabele, dosare de hârtie și trei grupuri de chat. Noi ne-am scris în schimb propriul sistem de dispecerat: fiecare cursă, rate confirmation, document, poziție de camion și factură stau într-un singur loc.",
    plat_p2="De aceea răspunsul primit de șofer, răspunsul primit de broker și cifra de pe factură sunt mereu aceeași cifră — nimeni nu rescrie nimic din memorie.",
    plat_btn="Deschide portalul",
    win_overview="Prezentare", win_loads="Curse", win_trucks="Camioane", win_files="Fișiere",
    win_brokers="Brokeri", win_tolls="Taxe drum", win_finance="Finanțe",
    win_gross="Brut", win_rpm="Pe milă", win_transit="În cursă", win_miles="Mile",
    win_r1="Dallas, TX · liber", win_r2="→ Dallas, TX · încărcat",
    win_r3="→ Phoenix, AZ · încărcat", win_r4="Houston, TX · liber",

    f1_t="Toată flota pe un singur ecran",
    f1_d="Brut și net pe perioadă, tarif pe milă, cine este încărcat și cine este gol. În plus, o cronologie zi de zi pentru fiecare camion: unde a stat, unde a mers, când se eliberează.",
    f2_t="Intră rate con-ul, iese cursa",
    f2_d="Trageți PDF-ul sau poza rate confirmation-ului. Sistemul citește brokerul, tariful, opririle, datele și milele și completează singur cursa.",
    f3_t="Profitul se vede înainte de a lua cursa",
    f3_d="Fiecare camion își are cifrele lui: consum, plata șoferului, rata camionului, asigurare, permise. Atașezi o cursă și vezi tariful pe milă, costurile și cât rămâne cu adevărat.",
    f4_t="Urmărire în timp real din ELD",
    f4_d="Toată flota pe o hartă: cine conduce, cine e în serviciu, cine staționează și câte mile mai sunt până la descărcare. Linkul unui camion poate merge la client — el vede doar acel camion.",
    f5_t="Documente care se aranjează singure",
    f5_d="Rate con-uri, BOL-uri, POD-uri, talon și asigurări, ordonate pe camion și pe cursă. Șoferul fotografiază documentul cu telefonul și acesta ajunge la cursa potrivită.",
    f6_t="Verificarea brokerului înainte de plecare",
    f6_d="Numărul MC intră în registrul FMCSA: dacă autoritatea este activă, dacă asigurarea este depusă, de câți ani lucrează — alături de istoricul nostru despre cum a plătit data trecută.",
    f7_t="Taxe de drum calculate pentru camion",
    f7_d="Variante de rută cu drumurile cu taxă calculate pentru un ansamblu cu cinci axe, așa că prețul drumului intră în calculul cursei, nu apare ca surpriză la sfârșitul lunii.",
    f8_t="Facturare și cine cât datorează",
    f8_d="O cursă descărcată devine factură, cu BOL și POD atașate într-un singur PDF. Lista arată ce este facturat, ce este plătit și ce este restant — și cu câte zile.",

    who_drv_t="Ce le dă șoferilor noștri",
    who_drv_1="Adresa de încărcare, contactele și orele programate la o atingere — nu mai trebuie sunat dispeceratul ca să întrebi.",
    who_drv_2="Fotografiezi BOL-ul sau POD-ul cu telefonul; se atașează singur și nimeni nu te mai aleargă după hârtii.",
    who_drv_3="Plata se calculează din aceleași cifre ale cursei pe care le vezi și tu, așa că ziua decontului nu aduce surprize.",
    who_drv_4="Documentele cu termen — CDL, fișa medicală — sunt semnalate înainte să expire.",
    who_cus_t="Ce le dă clienților noștri",
    who_cus_1="Un link de urmărire pentru marfa dumneavoastră, cu camionul pe hartă în timp real — fără cont și fără parolă.",
    who_cus_2="ETA calculat din poziția reală a camionului și din orele lui, nu dintr-o estimare optimistă.",
    who_cus_3="Pachetul de facturare ajunge complet din prima: factură, rate con, BOL și POD într-un singur PDF.",
    who_cus_4="Un dispecer care, când sunați, are în față tot istoricul cursei.",

    cta_h2="Gata de drum cu noi?",
    cta_lead="Trimiteți formularul și vă sunăm înapoi în aceeași zi lucrătoare.",

    foot_about="Transportator cu flotă proprie: dry van și power only. Cleveland, Tennessee — în toate cele 48 de state din 2007.",
    foot_drivers="Șoferi", foot_company="Compania",
    foot_rights="Toate drepturile rezervate.", foot_place="Cleveland, Tennessee, S.U.A.",

    mbox_title="Scrieți-ne", mbox_close="Închide", mbox_copy="Copiază", mbox_done="Copiat",
    mbox_gmail="Deschide în Gmail", mbox_app="Program de e-mail", mbox_copy_letter="Copiază mesajul",
    mbox_letter="Textul mesajului", mbox_no_app="Nu s-a deschis niciun program de e-mail. Mesajul este deja copiat — lipiți-l în e-mailul dumneavoastră sau folosiți „Deschide în Gmail”.",
    mbox_note="Copiat în clipboard.",
)
